apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "idp-api.fullname" . }}
  labels:
    app: {{ include "idp-api.name" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ include "idp-api.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "idp-api.name" . }}
    spec:
      serviceAccountName: {{ include "idp-api.fullname" . }}
      containers:
        - name: idp-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: {{ include "idp-api.fullname" . }}-config
            - secretRef:
                name: {{ include "idp-api.fullname" . }}-secrets
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
