apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-idp-api
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: idp-api
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector: {}
      ports:
        - protocol: TCP
          port: 8000
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 53
